# Generated by Django 6.0 on 2025-12-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='aob',
            field=models.TextField(blank=True),
        ),
    ]
