# Generated by Django 6.0 on 2025-12-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0002_brief_aob'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='inputi',
            field=models.TextField(blank=True),
        ),
    ]
