# Generated by Django 6.0 on 2025-12-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0003_brief_inputi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brief',
            name='inputi',
        ),
        migrations.AddField(
            model_name='brief',
            name='adding',
            field=models.TextField(default='No adding'),
        ),
    ]
