# Generated by Django 6.0 on 2025-12-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0004_remove_brief_inputi_brief_adding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brief',
            name='department',
        ),
    ]
