# Generated by Django 6.0 on 2025-12-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0005_remove_brief_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brief',
            old_name='adding',
            new_name='action_item',
        ),
        migrations.RenameField(
            model_name='brief',
            old_name='challenges',
            new_name='additional_info',
        ),
        migrations.RenameField(
            model_name='brief',
            old_name='aob',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='ideas',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='tasks',
        ),
    ]
