# Generated by Django 6.0 on 2025-12-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0006_rename_adding_brief_action_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AOB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_item', models.TextField(default='No adding')),
                ('assigned_to', models.TextField(blank=True)),
                ('status', models.TextField()),
                ('additional_info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
