# Generated by Django 6.0 on 2025-12-30 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0007_aob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(max_length=200)),
                ('purpose', models.TextField(default='No adding')),
            ],
        ),
        migrations.AlterField(
            model_name='aob',
            name='additional_info',
            field=models.TextField(default='No adding'),
        ),
        migrations.AlterField(
            model_name='aob',
            name='status',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='additional_info',
            field=models.TextField(default='No adding'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='briefs.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='briefs.meeting')),
            ],
        ),
        migrations.AddField(
            model_name='aob',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='briefs.meeting'),
        ),
        migrations.AddField(
            model_name='brief',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='briefs.meeting'),
        ),
    ]
