# Generated by Django 6.0 on 2025-12-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0008_meeting_alter_aob_additional_info_alter_aob_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='title',
            new_name='Agender_item',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='meeting',
        ),
    ]
