# Generated by Django 6.0 on 2025-12-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0009_rename_title_agenda_agender_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='meeting',
        ),
    ]
